<a href="https://colab.research.google.com/github/son50git/PKT_002_Convolutional/blob/master/PKT_002_tf_initial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
# import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

# Creating TensorFlow object 
hello_constant = tf.constant('Hello World!', name = 'hello_constant')
# Creating a session object for execution of the computational graph
with tf.Session() as sess:

    # Implementing the tf.constant operation in the session
    output = sess.run(hello_constant)
    print(output)

b'Hello World!'


In [57]:
# import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

# A is an int32 tensor with rank = 0
A = tf.constant(123) 
# B is an int32 tensor with dimension of 1 ( rank = 1 ) 
B = tf.constant([123,456,789]) 
# C is an int32 2- dimensional tensor 
C = tf.constant([ [123,456,789], [222,333,444] ])

#Creating a session object for execution of the computational graph
with tf.Session() as sess:
    #Implementing the tf.constant operation in the session
    # output = sess.run(A) # 123
    # output = sess.run(B) # [123 456 789]
    output = sess.run(C) # [[123 456 789] [222 333 444]]
    print(output)

[[123 456 789]
 [222 333 444]]


In [58]:
# import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

constant_x = tf.constant(5, name='constant_x')
variable_y = tf.Variable(constant_x + 5, name='variable_y')
print (variable_y) # <tf.Variable 'variable_y_1:0' shape=() dtype=int32_ref>

#initialize all variables
init = tf.global_variables_initializer()
# All variables are now initialized

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(variable_y)) # 10

<tf.Variable 'variable_y_4:0' shape=() dtype=int32_ref>
10


In [59]:
# import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

x = tf.placeholder(tf.string)
y = tf.placeholder(tf.int32, None)
z = tf.placeholder(tf.float32, None)

with tf.Session() as sess:
    output = sess.run(x, feed_dict={x: 'Welcome to CNN', y: 123, z: 123.45})
    print(output) # Welcome to CNN

with tf.Session() as sess:
    output = sess.run(y, feed_dict={x: 'Welcome to CNN', y: 123, z: 123.45})
    print(output) # 123

Welcome to CNN
123


In [60]:
# import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

x3 = tf.placeholder("float", [None, 3]) # NONE means 'as long as you have three elements in the row'
x2 = tf.placeholder("float", [None, 2])
z3 = 2 * x3
z2 = 2 * x2

with tf.Session() as session:
    input_data = [[1, 2, 3],
                 [4, 5, 6],]
    result = session.run(z3, feed_dict={x3: input_data})
    print(result)  # [[ 2.  4.  6.][ 8. 10. 12.]]

with tf.Session() as session:
    input_data = [[1, 2],
                 [4, 5],]
    result = session.run(z2, feed_dict={x2: input_data}) # [[ 2.  4.] [ 8. 10.]]
    print(result)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[ 2.  4.]
 [ 8. 10.]]


In [63]:
softmax_data = [0.1,0.5,0.4]
onehot_data =  [0.0,1.0,0.0]

softmax = tf.placeholder(tf.float32)
onehot_encoding = tf.placeholder(tf.float32)
tmp = tf.log(softmax) # NO values # only for verification: [-2.3025851 -0.6931472 -0.9162907]
tmp = tf.multiply(onehot_encoding,tf.log(softmax)) # NO values # only for verification: [-0. -0.6931472 -0.]
tmp = - tf.reduce_sum(tf.multiply(onehot_encoding,tf.log(softmax))) # NO values # only for verification: 0.6931472  
with tf.Session() as session:
    print(session.run(tmp, feed_dict={softmax:softmax_data, onehot_encoding:onehot_data} ))

tmp2 = tf.nn.softmax_cross_entropy_with_logits(logits=tf.log(softmax), labels=onehot_encoding)
with tf.Session() as session:
    print(session.run(tmp2, feed_dict={softmax:softmax_data, onehot_encoding:onehot_data} ))

# summary
# the following two are equivalent
# tf.nn.softmax_cross_entropy_with_logits(logits=A, labels=B)
# - tf.reduce_sum(tf.multiply(B, A)))

0.6931472
0.6931472


In [64]:
# import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

softmax_data = [0.1,0.5,0.4]
onehot_data = [0.0,1.0,0.0]

softmax = tf.placeholder(tf.float32)
onehot_encoding = tf.placeholder(tf.float32)

cross_entropy = - tf.reduce_sum(tf.multiply(onehot_encoding,tf.log(softmax)))

cross_entropy_loss = tf.nn.softmax_cross_entropy_with_logits(logits=tf.log(softmax), labels=onehot_encoding)

with tf.Session() as session:
    print(session.run(cross_entropy,feed_dict={softmax:softmax_data, onehot_encoding:onehot_data} ))
    print(session.run(cross_entropy_loss,feed_dict={softmax:softmax_data, onehot_encoding:onehot_data} ))

0.6931472
0.6931472


In [70]:
# softmax = tf.exp(logits) / tf.reduce_sum(tf.exp(logits), axis)
# Computes softmax activations
# softmax = tf.nn.softmax(logits)

# import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

logit_data = [2.0, 1.0, 0.1]
logits = tf.placeholder(tf.float32)

tmp = tf.exp(logits)  # verification: [7.389056  2.7182817 1.105171 ]
tmp = tf.reduce_sum(tf.exp(logits))  # verification: 11.212509
tmp = tf.exp(logits) / tmp

with tf.Session() as sess:
    output = sess.run(tmp, feed_dict={logits: logit_data})
    print( output )  # [0.6590011  0.24243295 0.09856589]


[0.6590011  0.24243295 0.09856589]


In [71]:
# import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

logit_data = [2.0, 1.0, 0.1]
logits = tf.placeholder(tf.float32)
softmax = tf.nn.softmax(logits)

with tf.Session() as sess:
    output = sess.run(softmax, feed_dict={logits: logit_data})
    print( output )


[0.6590012  0.24243298 0.09856589]
